"""V2: check each ROBUST paper quote against my own pdftotext extraction (pages split on form feed)."""
import re, sys, os
D = sys.argv[1]
Q = [
 ('E-020', '2022_jing_torsional_diffusion', 7, "there will be a distributional shift at test time, where only approximate local structures from p^G(L) are available. We found that this shift significantly hurts performance."),
 ('E-021', '2022_jing_torsional_diffusion', 19, "The complete assignment resulting from the linear sum solution guarantees that there is no distributional shift in the local structures seen during training and inference."),
 ('E-022', '2022_jing_torsional_diffusion', 8, "Instead, we view the distributional shift as a domain adaptation problem that can be solved by optimally aligning pG(L) and p^G(L)."),
 ('E-023', '2021_ho_cascaded_diffusion', 3, "We empirically find that conditioning augmentation is effective because it alleviates compounding error in cascading pipelines due to train-test mismatch"),
 ('E-024', '2021_ho_cascaded_diffusion', 18, "This occurs when low- resolution model samples are out of distribution compared to the ground truth data on which the super-resolution model is trained."),
 ('E-025', '2021_ho_cascaded_diffusion', 18, "While we found Gaussian noise augmentation to be a key ingredient to boost the performance of our cascaded models at low resolutions, our initial experiments with similar augmentations for 128x128 and 256x256 upsampling yielded negative results."),
 ('E-026', '2021_ho_cascaded_diffusion', 7, "During training, we apply this blurring augmentation to 50% of the examples. During inference, no augmentation is applied to low resolution inputs."),
 ('E-027', '2021_ho_cascaded_diffusion', 6, "In some cases, we found it more practical to train super-resolution models amortized over the strength of conditioning augmentation and pick the best strength in a post-training hyperparameter search"),
 ('E-028', '2021_ho_cascaded_diffusion', 8, "in non-truncated conditioning augmentation we always sample z0 using the full, non-truncated low resolution reverse process; then we corrupt z0 using the forward process into zs"),
 ('E-029', '2023_ning_input_perturbation', 1, "consisting in perturbing the ground truth samples to simulate the inference time prediction errors."),
 ('E-030', '2023_ning_input_perturbation', 2, "which forces the network to smooth its prediction function"),
 ('E-031', '2022_dauparas_proteinmpnn', 7, "We found that training models on backbones to which Gaussian noise (std=0.02A) had been added improved sequence recovery on confident protein structure models generated by AlphaFold (average pLDDT>80.0) from UniRef50"),
 ('E-032', '2022_dauparas_proteinmpnn', 7, "Crystallographic refinement may impart some memory of amino acid identity in the backbone coordinates which is recovered by the model trained on perfect backbones but not present in predicted structures"),
 ('E-033', '2022_dauparas_proteinmpnn', 3, "Experiment 4 Experiment 3 with random instead of forward decoding 1.678 mln 50.8/47.9 4.74/5.25 46.9/48.5"),
 ('E-034', '2024_ni_sliced_denoising', 2, "due to inappropriate assumptions such as assuming a molecular force field is isotropic in coordinate denoising (Zaidi et al., 2022)"),
 ('E-035', '2024_ni_sliced_denoising', 2, "BAT noise introduces Gaussian noise to bond lengths, angles, and torsion angles, and their respective variances are predetermined by parameters within the energy function. This approach allows BAT noise to better approximate the true molecular distribution"),
 ('E-036', '2017_tobin_domain_randomization', 1, "With enough variability in the simulator, the real world may appear to the model as just another variation."),
 ('E-037', '2025_sun_noise_conditioning', 1, "To our surprise, most models exhibit graceful degradation, and in some cases, they even perform better without noise conditioning."),
 ('E-038', '2025_sun_noise_conditioning', 4, "We note that the concentration of ppt|zq depends on data dimensionality"),
 ('E-039', '2025_sun_noise_conditioning', 8, "Notably, consistent behavior is observed for all models (iDDPM, EDM, and FM) studied here: the results of (b), (c), and (d) are similar."),
 ('E-040', '2015_bengio_scheduled_sampling', 1, "This discrepancy between training and inference can yield errors that can accumulate quickly along the generated sequence."),
 ('E-041', '2015_bengio_scheduled_sampling', 2, "We propose to change the training process in order to gradually force the model to deal with its own mistakes, as it would have to during inference."),
 ('E-042', '2015_huszar_scheduled_sampling_critique', 1, "the objective function underlying scheduled sampling is improper and leads to an inconsistent learning algorithm."),
 ('E-043', '2015_huszar_scheduled_sampling_critique', 4, "Based on this analysis we suggest that scheduled sampling works by pushling models towards a trivial solution of memorising distribution of symbols conditioned on their position in the sequence,"),
 ('E-044', '2011_ross_dagger', 1, "since the learner's prediction affects future input observations/states during execution of the learned policy, this violate the crucial i.i.d. assumption made by most statistical learning approaches."),
 ('E-045', '2011_ross_dagger', 3, "DAGGER (Dataset Aggregation), an iterative algorithm that trains a deterministic policy that achieves good performance guarantees under its induced distribution of states."),
 ('E-046', '2022_ho_classifier_free_guidance', 8, "We find puncond = 0.5 consistently performs worse than puncond {0.1, 0.2} across the entire IS/FID frontier; puncond {0.1, 0.2} perform about equally as well as each other."),
 ('E-047', '2022_ho_classifier_free_guidance', 9, "any guidance method that increases sample fidelity at the expense of diversity must face the question of whether decreased diversity is acceptable."),
 ('E-048', '2022_ho_classifier_free_guidance', 4, "for the unconditional model we can simply input a null token for the class identifier c when predicting the score"),
 ('E-049', '2023_du_reduce_reuse_recycle', 5, "does not correspond to sampling from the composed model, and thus reverse diffusion sampling will generate incorrect samples from composed distributions."),
]

def norm(s):
    s = s.replace('�', '').replace('×', 'x').replace('’', "'").replace('‘', "'")
    s = re.sub(r'-\s+', '', s)        # join hyphenation
    s = re.sub(r'[^A-Za-z0-9]+', '', s)  # drop all punctuation/whitespace/glyphs for a lenient match
    return s.lower()

def strict(s):
    return re.sub(r'\s+', ' ', s.replace('�', '')).strip()

for eid, paper, page, quote in Q:
    txt = open(os.path.join(D, paper + '.txt'), encoding='utf-8', errors='replace').read()
    pages = txt.split('\f')
    nq = norm(quote)
    hits = [i + 1 for i, p in enumerate(pages) if nq in norm(p)]
    # partial: first and last 40 normalized chars
    hd = [i + 1 for i, p in enumerate(pages) if nq[:40] in norm(p)]
    tl = [i + 1 for i, p in enumerate(pages) if nq[-40:] in norm(p)]
    sp = [i + 1 for i, p in enumerate(pages) if strict(quote) in strict(p)]
    print(f'{eid} {paper} claimed p.{page}: lenient_full={hits} strict_ws={sp} head={hd} tail={tl}')
